#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

###
# Script to build filter wasm with test setting enabled.
###

rm build/*

echo "--> Building FilterBuilder wasm module."

docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) emscripten/emsdk emcc \
    src/xor_builder.c \
    -s WASM=1 \
    -O0 \
    -Wall \
    -s MODULARIZE=1 \
    -s EXTRA_EXPORTED_RUNTIME_METHODS="['intArrayFromString', 'allocate', 'ALLOC_NORMAL']" \
    -s EXPORTED_FUNCTIONS="['_malloc', '_free']" \
    -lnodefs.js \
    -o build/xor_builder.js

