#!/bin/bash

## Script to build wasm with test setting enabled.
## Output WASM, disable optimizations, compile with warnings, modularize for Node,
## ouput required built-in functions, and output to the `_build` directory.

docker run --rm -v $(pwd):/src -u $(id -u):$(id -g) emscripten/emsdk emcc \
    src/xor_builder.c \
    -s WASM=1 \
    -O0 \
    -Wall \
    -s MODULARIZE=1 \
    -s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall', 'intArrayFromString', 'allocate', 'ALLOC_NORMAL']" \
    -s EXPORTED_FUNCTIONS="['_malloc', '_free']" \
    -lnodefs.js \
    -o _build/xor_builder.js
